package warcraft.services;

public interface RequireCentreNationalRechercheSpecialeService {
	public void bindCentreNationalRechercheSpecialeServie(ICentreNationalRechercheSpecialeService service);
}
